name: dashy

networks:
  home-network:
    external: true

services:
  dashy:
    container_name: dashy
    image: lissy93/dashy:latest
    volumes:
      - ~/docker/appdata/dashy/conf.yml:/app/user-data/conf.yml
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 4000:8080
    environment:
      - BASE_URL=/
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "/app/services/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
