name: it-tools

networks:
  home-network:
    name: home-network
    driver: bridge

version: "3.9"
services:
  it-tools:
    image: "corentinth/it-tools:latest"
    ports:
      - "8282:80"
    restart: unless-stopped
    container_name: it-tools
