networks:
  home-network:
    external: true

services:
  paperless-redis:
    image: redis:7-alpine
    container_name: paperless_redis
    volumes:
      - ./appdata/redis:/data
    restart: always
    networks:
      - home-network

  paperless-db:
    image: postgres:15-alpine
    container_name: paperless_db
    volumes:
      - ./appdata/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${PAPERLESS_DB_NAME}
      POSTGRES_USER: ${PAPERLESS_DB_USER}
      POSTGRES_PASSWORD: ${PAPERLESS_DB_PASS}
    restart: always
    networks:
      - home-network

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    depends_on:
      - paperless-db
      - paperless-redis
    ports:
      - 8777:8000
    volumes:
      - ./appdata/data:/usr/src/paperless/data
      - ${NAS_PATH}/paperless/media:/usr/src/paperless/media
      - ${NAS_PATH}/paperless-consume:/usr/src/paperless/consume
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_DBHOST: paperless-db
      PAPERLESS_TIME_ZONE: ${TZ}
      PAPERLESS_OCR_LANGUAGES: ${PAPERLESS_OCR_LANGUAGES}
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
    restart: always
    networks:
      - home-network
