networks:
  home-network:
    external: true

services:
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    environment:
      TZ: ${TZ}
      REDIS_HOSTNAME: ${REDIS_HOSTNAME}
      DB_HOSTNAME: ${DB_HOSTNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USERNAME: ${DB_USERNAME}
      DB_DATABASE_NAME: ${DB_DATABASE_NAME}
    volumes:
      - ${NAS_PATH}/photos-library/library:/usr/src/app/upload/library
      - ${NAS_PATH}/photos-library/upload:/usr/src/app/upload/upload
      - ${NAS_PATH}/photos:/usr/src/app/import-source:ro
      - ./appdata/thumbs:/usr/src/app/upload/thumbs
      - ./appdata/encoded-video:/usr/src/app/upload/encoded-video
      - ./appdata/profile:/usr/src/app/upload/profile
      - ./appdata/backups:/usr/src/app/upload/backups
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3001:2283"
    depends_on:
      - immich-redis
      - immich-postgres
    restart: always
    healthcheck:
      disable: false
    networks:
      - home-network

  immich-machine-learning:
    container_name: immich_machine_learning
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    volumes:
      - ./appdata/model-cache:/cache
    restart: always
    healthcheck:
      disable: false
    networks:
      - home-network

  immich-redis:
    container_name: immich_redis
    image: docker.io/valkey/valkey:9@sha256:546304417feac0874c3dd576e0952c6bb8f06bb4093ea0c9ca303c73cf458f63
    restart: always
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - home-network

  immich-postgres:
    container_name: immich_postgres
    image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      POSTGRES_INITDB_ARGS: "--data-checksums"
      POSTGRES_SHARED_BUFFERS: "512MB"
      POSTGRES_EFFECTIVE_CACHE_SIZE: "2GB"
      POSTGRES_MAX_CONNECTIONS: "200"
    volumes:
      - ./appdata/postgres:/var/lib/postgresql/data
    shm_size: 256mb
    restart: always
    healthcheck:
      disable: false
    networks:
      - home-network
