networks:
  home-network:
    external: true

services:
  calibre:
    image: lscr.io/linuxserver/calibre:latest
    container_name: calibre
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      PASSWORD: ${CALIBRE_PASSWORD}
    volumes:
      - ./appdata/calibre:/config
      - ${NAS_PATH}/calibre/Calibre Library:/books
    ports:
      - 8012:8080
    restart: always
    networks:
      - home-network

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TZ}
      DOCKER_MODS: linuxserver/mods:universal-calibre
    volumes:
      - ./appdata/calibre-web:/config
      - ${NAS_PATH}/calibre/Calibre Library:/books
    ports:
      - 8014:8083
    restart: always
    networks:
      - home-network
